import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const directory = dirname(fileURLToPath(import.meta.url));
const root = resolve(directory, '..');
const packageJson = JSON.parse(
    readFileSync(resolve(root, 'package.json'), 'utf8'),
);
const version = packageJson.version;
const algorithmVersion = packageJson.algorithmVersion;

if (typeof version !== 'string' || version.length === 0) {
    process.stderr.write('error: package.json.version is missing or empty\n');
    process.exit(1);
}

const semverPattern = /^\d+\.\d+\.\d+(?:-[\da-zA-Z.-]+)?(?:\+[\da-zA-Z.-]+)?$/;
if (!semverPattern.test(version)) {
    process.stderr.write(
        `error: package.json.version "${version}" is not valid semver\n`,
    );
    process.exit(1);
}

if (typeof algorithmVersion !== 'string' || !/^\d+$/.test(algorithmVersion)) {
    process.stderr.write(
        'error: package.json.algorithmVersion must be a numeric string\n',
    );
    process.exit(1);
}

const outputDirectory = resolve(root, 'src/generated');
mkdirSync(outputDirectory, { recursive: true });

const content =
    '// Generated by scripts/sync-version.mjs — do not edit manually\n' +
    "export const VERSION = '" +
    version +
    "' as const;\n" +
    "export const ALGORITHM_VERSION = '" +
    algorithmVersion +
    "' as const;\n";

writeFileSync(resolve(outputDirectory, 'version.ts'), content, 'utf8');
